import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/providers/Provider";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Task Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-700">
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
